opendatacollector-elasticsearch:
  container_name: opendatacollector-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/opendatacollector/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
opendatacollector-postgresql:
  container_name: opendatacollector-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/opendatacollector/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=opendatacollector
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
